Catalog = {}

Catalog.BaseEntry = "SA_Base"

Catalog.Containers = {
    "SA_TakePotion",
    "SA_UseScroll",
}

Catalog.RemovesItemOnCast = {
    ["SA_UseScroll"] = true,
}

Catalog.Categories = {
    {
        container = "SA_TakePotion",
        prefix = "SA_Potion_",
        useType = "Potion",
        inheritsItemSpell = false,
        families = {
            ["BASE_ALCH_Solution_Elixir"] = true,
            ["BASE_ALCH_Solution_Potion"] = true,
            ["BASE_CONS_Drink_Potion"] = true,
        },
    },
    {
        container = "SA_UseScroll",
        prefix = "SA_Scroll_",
        useType = "Scroll",
        inheritsItemSpell = true,
        families = {
            ["BASE_BOOK_Scroll_Magic"] = true,
        },
    },
}

Catalog.IconKeys = {
    ["SA_Icon_ALCH_Solution_Elixir_Alertness"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_ArcaneAcuity"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Barkskin"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Bloodlust"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Concentration"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Criticals"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Darkvision"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Enlarge"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Freedom"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Meditation"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Meditation_Greater"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Meditation_Superior"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Meditation_Supreme"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_SeeInvisible"] = true,
    ["SA_Icon_ALCH_Solution_Elixir_Tadpole"] = true,
    ["SA_Icon_ALCH_Solution_Potion_Flying"] = true,
    ["SA_Icon_ALCH_Solution_Potion_Remedy"] = true,
    ["SA_Icon_ALCH_Solution_Potion_Rest_Greater"] = true,
    ["SA_Icon_ALCH_Solution_Potion_Rest_Lesser"] = true,
    ["SA_Icon_OBJ_BloodPotion_Dragonborn_Acid"] = true,
    ["SA_Icon_OBJ_BloodPotion_Dragonborn_Fire"] = true,
    ["SA_Icon_OBJ_BloodPotion_Dragonborn_Ice"] = true,
    ["SA_Icon_OBJ_BloodPotion_Dragonborn_Lightning"] = true,
    ["SA_Icon_OBJ_BloodPotion_Dragonborn_Poison"] = true,
    ["SA_Icon_OBJ_BloodPotion_Dwarf"] = true,
    ["SA_Icon_OBJ_BloodPotion_Elf"] = true,
    ["SA_Icon_OBJ_BloodPotion_Githyanki"] = true,
    ["SA_Icon_OBJ_BloodPotion_Gnome"] = true,
    ["SA_Icon_OBJ_BloodPotion_HalfElf"] = true,
    ["SA_Icon_OBJ_BloodPotion_HalfOrc"] = true,
    ["SA_Icon_OBJ_BloodPotion_Halfing"] = true,
    ["SA_Icon_OBJ_BloodPotion_Human"] = true,
    ["SA_Icon_OBJ_BloodPotion_Tiefling"] = true,
    ["SA_Icon_OBJ_Potion_Healing_Supreme"] = true,
    ["SA_Icon_OBJ_Potion_Of_Cloud_Giant_Strength"] = true,
    ["SA_Icon_OBJ_Potion_Of_Fire_Resistance"] = true,
    ["SA_Icon_OBJ_Potion_Of_Heroism"] = true,
    ["SA_Icon_OBJ_Potion_Of_Hill_Giant_Strength"] = true,
    ["SA_Icon_OBJ_Potion_Of_Invisibility"] = true,
    ["SA_Icon_OBJ_Potion_Of_Invulnerability"] = true,
    ["SA_Icon_OBJ_Potion_Of_Lightning_Resistance"] = true,
    ["SA_Icon_OBJ_Potion_Of_Necrotic_Resistance"] = true,
    ["SA_Icon_OBJ_Potion_Of_Poison_Resistance"] = true,
    ["SA_Icon_OBJ_Potion_Of_Psychic_Resistance"] = true,
    ["SA_Icon_OBJ_Potion_Of_Speed"] = true,
    ["SA_Icon_OBJ_Scroll_AcidArrow"] = true,
    ["SA_Icon_OBJ_Scroll_ArcaneEye"] = true,
    ["SA_Icon_OBJ_Scroll_ArcaneLock"] = true,
    ["SA_Icon_OBJ_Scroll_Banishment"] = true,
    ["SA_Icon_OBJ_Scroll_BlackTentacles"] = true,
    ["SA_Icon_OBJ_Scroll_Blight"] = true,
    ["SA_Icon_OBJ_Scroll_Blindness"] = true,
    ["SA_Icon_OBJ_Scroll_Blink"] = true,
    ["SA_Icon_OBJ_Scroll_Blur"] = true,
    ["SA_Icon_OBJ_Scroll_ChainLightning"] = true,
    ["SA_Icon_OBJ_Scroll_CircleOfDeath"] = true,
    ["SA_Icon_OBJ_Scroll_Cloudkill"] = true,
    ["SA_Icon_OBJ_Scroll_ConeOfCold"] = true,
    ["SA_Icon_OBJ_Scroll_Confusion"] = true,
    ["SA_Icon_OBJ_Scroll_Counterspell"] = true,
    ["SA_Icon_OBJ_Scroll_CrownOfMadness"] = true,
    ["SA_Icon_OBJ_Scroll_Darkness"] = true,
    ["SA_Icon_OBJ_Scroll_Darkvision"] = true,
    ["SA_Icon_OBJ_Scroll_DetectThoughts"] = true,
    ["SA_Icon_OBJ_Scroll_DimensionDoor"] = true,
    ["SA_Icon_OBJ_Scroll_Disintegrate"] = true,
    ["SA_Icon_OBJ_Scroll_DispelMagic"] = true,
    ["SA_Icon_OBJ_Scroll_DominatePerson"] = true,
    ["SA_Icon_OBJ_Scroll_Fear"] = true,
    ["SA_Icon_OBJ_Scroll_FeignDeath"] = true,
    ["SA_Icon_OBJ_Scroll_Fireball"] = true,
    ["SA_Icon_OBJ_Scroll_FlameBlade"] = true,
    ["SA_Icon_OBJ_Scroll_FlamingSphere"] = true,
    ["SA_Icon_OBJ_Scroll_FleshToStone"] = true,
    ["SA_Icon_OBJ_Scroll_Fly"] = true,
    ["SA_Icon_OBJ_Scroll_GaseousForm"] = true,
    ["SA_Icon_OBJ_Scroll_GlobeOfInvulnerability"] = true,
    ["SA_Icon_OBJ_Scroll_GustOfWind"] = true,
    ["SA_Icon_OBJ_Scroll_Haste"] = true,
    ["SA_Icon_OBJ_Scroll_HoldMonster"] = true,
    ["SA_Icon_OBJ_Scroll_HoldPerson"] = true,
    ["SA_Icon_OBJ_Scroll_HypnoticPattern"] = true,
    ["SA_Icon_OBJ_Scroll_IceStorm"] = true,
    ["SA_Icon_OBJ_Scroll_Invisibility"] = true,
    ["SA_Icon_OBJ_Scroll_Invisibility_Greater"] = true,
    ["SA_Icon_OBJ_Scroll_IrresistibleDance"] = true,
    ["SA_Icon_OBJ_Scroll_Knock"] = true,
    ["SA_Icon_OBJ_Scroll_LightningBolt"] = true,
    ["SA_Icon_OBJ_Scroll_MagicWeapon"] = true,
    ["SA_Icon_OBJ_Scroll_MirrorImage"] = true,
    ["SA_Icon_OBJ_Scroll_MistyStep"] = true,
    ["SA_Icon_OBJ_Scroll_PhantasmalForce"] = true,
    ["SA_Icon_OBJ_Scroll_PhantasmalKiller"] = true,
    ["SA_Icon_OBJ_Scroll_PlanarBinding"] = true,
    ["SA_Icon_OBJ_Scroll_Polymorph"] = true,
    ["SA_Icon_OBJ_Scroll_RemoveCurse"] = true,
    ["SA_Icon_OBJ_Scroll_ResilientSphere"] = true,
    ["SA_Icon_OBJ_Scroll_Revivify_TrueResurrection"] = true,
    ["SA_Icon_OBJ_Scroll_SeeInvisibility"] = true,
    ["SA_Icon_OBJ_Scroll_Seeming"] = true,
    ["SA_Icon_OBJ_Scroll_Shatter"] = true,
    ["SA_Icon_OBJ_Scroll_Slow"] = true,
    ["SA_Icon_OBJ_Scroll_SpeakWithDead"] = true,
    ["SA_Icon_OBJ_Scroll_StinkingCloud"] = true,
    ["SA_Icon_OBJ_Scroll_Stoneskin"] = true,
    ["SA_Icon_OBJ_Scroll_Sunbeam"] = true,
    ["SA_Icon_OBJ_Scroll_Telekinesis"] = true,
    ["SA_Icon_OBJ_Scroll_VampiricTouch"] = true,
    ["SA_Icon_OBJ_Scroll_WallOfFire"] = true,
    ["SA_Icon_OBJ_Scroll_WallOfIce"] = true,
    ["SA_Icon_OBJ_Scroll_WallOfStone"] = true,
    ["SA_Icon_OBJ_Scroll_Web"] = true,
    ["SA_Icon_UNI_LOW_BestialCommunionScroll"] = true,
    ["SA_Icon_UNI_LOW_CurriculumOfStrategyScroll"] = true,
    ["SA_Icon_UNI_LOW_DethroneScroll"] = true,
    ["SA_Icon_UNI_TWN_Scroll_FleshToGold"] = true,
}

Catalog.TemplateToSpell = {}
Catalog.SpellToTemplate = {}
Catalog.SpellContainer = {}
Catalog.Labels = {}
Catalog.LegacySpells = {}
